language: java
# core streaming still builds on jdk6 and above:
# 05-Jan-2018, tatu: Not sure why, but travis build fails on jdk6 so leave it out
jdk:
  - openjdk7
  - openjdk8

# Below this line is configuration for deploying to the Sonatype OSS repo
# http://blog.xeiam.com/2013/05/configure-travis-ci-to-deploy-snapshots.html
before_install: "git clone -b travis `git config --get remote.origin.url` target/travis"
after_success: "mvn deploy --settings target/travis/settings.xml"

# whitelist
branches:
  only:
    - master
    - "2.9"

# to make jdk6 work, as per: https://github.com/travis-ci/travis-ci/issues/8199
addons:
  apt:
    packages:
      - openjdk-6-jdk

env:
  global:
    - secure: "YW0hrdsHvH41pb5uPJ2DGzXrBgOVT7nEyag/bAQoDcSlOQ/g55tnY6rIGkqE/aYD47IroTEhW4yLyM3tZpbrqwagX4dUX90ukjcUwUvFE1ePTSEfdBtuHVwl8f6HmLIIw2yK0dQ1gOJ21T+3g+wddvK+6sWBJJ+s3O1FePDh6X0="
    - secure: "sGQxvyfg98BFcJcWHQ5BjvDNhbwdgD1yEfkE3qzH4/gzwD/ND1jKhkCX++Glt3DuyAKhENNzXlSkztdCE5wKfK3X6MVvOgzMgiV/BhHIf09EtAjZ35fe4pr+GZImfGZO3qkViooTz3FDJyKJBA3YyMTuo9/eWK8HlUFCZHTjKP8="

